global using NetlifySharp;
global using Nuke.Common;
global using Nuke.Common.CI;
global using Nuke.Common.CI.GitHubActions;
global using Nuke.Common.IO;
global using Nuke.Common.ProjectModel;
global using Nuke.Common.Tooling;
global using Nuke.Common.Tools.Coverlet;
global using Nuke.Common.Tools.DotNet;
global using Nuke.Common.Tools.GitVersion;
global using Nuke.Common.Tools.ReportGenerator;
global using Nuke.Common.Utilities.Collections;
global using System.Collections.Generic;
global using System.Linq;
global using static Nuke.Common.IO.FileSystemTasks;
global using static Nuke.Common.IO.PathConstruction;
global using static Nuke.Common.Tools.DotNet.DotNetTasks;